services:
  - type: worker
    name: omegax-bot
    env: python
    plan: free
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: python -u main.py

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: MODE
        value: paper
      - key: SYMBOLS
        value: BTC/USDT,ETH/USDT
      - key: DB_PATH
        value: /tmp/state.db
      - key: LOG_LEVEL
        value: INFO