services:
  - type: web
    name: omegax-fusion
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python omegax_fusion_v23.py
    healthCheckPath: /ping
    envVars:
      - key: MODE
        value: paper
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: SYMBOL_AUTO_DISCOVERY
        value: "true"
      - key: SYMBOLS_TOP_N
        value: "50"
      - key: ENABLE_SCALPING
        value: "true"
      - key: SCALPING_MAX_SYMBOLS
        value: "12"
      - key: ENABLE_MEAN_REVERSION
        value: "true"
      - key: ENABLE_GRID
        value: "true"
      - key: ENABLE_ARBITRAGE
        value: "false"
      - key: TELEGRAM_REPORT_INTERVAL_SEC
        value: "900"
      # KeepAlive pings (optional but recommended)
      - key: SELF_URL
        value: ""   # e.g. https://omegax-fusion.onrender.com/ping
      - key: KEEPALIVE_URL
        value: ""   # e.g. BetterStack/UptimeRobot heartbeat URL
      - key: KEEPALIVE_INTERVAL_SEC
        value: "60"
      # Persistence (optional, to survive redeploys)
      - key: PERSIST_MODE
        value: "local"     # or both/remote if you configure below
      - key: REMOTE_BACKEND
        value: ""          # s3|gist (set and fill below to enable)
      # S3 (if using REMOTE_BACKEND=s3)
      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_REGION
        value: ""
      - key: S3_BUCKET
        value: ""
      - key: S3_KEY
        value: "state.json"
      - key: S3_ENDPOINT
        value: ""
      # Gist (if using REMOTE_BACKEND=gist)
      - key: GITHUB_TOKEN
        value: ""
      - key: GIST_ID
        value: ""
      - key: GIST_FILENAME
        value: "state.json"
      # Binance keys (live only)
      - key: BINANCE_API_KEY
        value: ""
      - key: BINANCE_API_SECRET
        value: ""
      # Telegram (recommended)
      - key: TELEGRAM_TOKEN
        value: ""
      - key: TELEGRAM_CHAT_ID
        value: ""