services:
  - type: web
    name: omegax-fusion
    runtime: python
    plan: free
    region: oregon
    healthCheckPath: /ping
    buildCommand: |
      export PIP_ONLY_BINARY=:all:
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python omegax_fusion_v25.py
    envVars:
      - key: MODE
        value: paper
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: SYMBOL_AUTO_DISCOVERY
        value: "true"
      - key: SYMBOLS_TOP_N
        value: "50"
      - key: ENABLE_SCALPING
        value: "true"
      - key: SCALPING_MAX_SYMBOLS
        value: "12"
      - key: ENABLE_MEAN_REVERSION
        value: "true"
      - key: ENABLE_GRID
        value: "true"
      - key: ENABLE_ARBITRAGE
        value: "false"
      - key: TELEGRAM_REPORT_INTERVAL_SEC
        value: "900"
      # KeepAlive pings
      - key: SELF_URL
        value: ""   # e.g. https://omegax-fusion.onrender.com/ping
      - key: KEEPALIVE_URL
        value: ""   # e.g. BetterStack/UptimeRobot heartbeat URL
      - key: KEEPALIVE_INTERVAL_SEC
        value: "60"
      # Persistence (local default; remote gist optional)
      - key: PERSIST_MODE
        value: "local"     # local|remote|both; set both to survive redeploys (needs GIST_* below)
      - key: REMOTE_BACKEND
        value: "gist"
      - key: GITHUB_TOKEN
        value: ""
      - key: GIST_ID
        value: ""
      - key: GIST_FILENAME
        value: "state.json"
      # Binance (live mode only)
      - key: BINANCE_API_KEY
        value: ""
      - key: BINANCE_API_SECRET
        value: ""
      # Telegram (recommended)
      - key: TELEGRAM_TOKEN
        value: ""
      - key: TELEGRAM_CHAT_ID
        value: ""