services:
  - type: web
    name: omegax-trading-bot
    env: python
    plan: starter
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python "OmegaX bot.py"
    envVars:
      - key: MODE
        value: paper
      - key: INITIAL_BALANCE
        value: "3000"
      - key: RISK_PER_TRADE
        value: "0.005"
      - key: MAX_TOTAL_RISK
        value: "0.06"
      - key: MAX_CONCURRENT_POS
        value: "8"
      - key: MAX_DRAWDOWN
        value: "0.08"
      - key: HTTP_TIMEOUT
        value: "10"
      - key: RETRY_LIMIT
        value: "3"
      - key: SYMBOLS
        value: "BTC/USDT,ETH/USDT"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: DB_PATH
        value: "/opt/render/project/src/state.db"
    healthCheckPath: /health
    autoDeploy: false